name: docstring_test

on:
   # Trigger the workflow on push or pull request,
   # but only for the master branch
   push:
     branches:
       - master
   pull_request:
     branches:
       - master

jobs:
  docstring-test:
    name: Run Docstring Tests
    runs-on: ubuntu-latest

    steps:
    - name: Checkout acsefuncitons
      uses: actions/checkout@v2

    - name: Set up Python 3.10
      uses: actions/setup-python@v1
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run docstring tests
      run: |
        python -m doctest -v sais/benchmarks.py
        python -m doctest -v sais/symbiotic_ais.py